# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# There is no error in this script. This line is just a comment.
# The '#' symbol denotes a comment in YAML files, which is ignored by the parser.
# If you're experiencing issues, the problem might be elsewhere in the file or in your Jekyll setup.
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# theme: minimal-mistakes-jekyll
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kerem Zengin
email: kerem.zengin@metu.edu.tr
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website. I'm Kerem 
baseurl: "" # the subpath of your site, e.g. /blog
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  kerem-z

# Theme settings
minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
markdown: kramdown
kramdown:
  math_engine: mathjax


# Site Author
author:
  name             : "Kerem Zengin"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "doing some stuff"
  location         : "Middle East Technical University"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:kerem.zengin@metu.edu.tr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kerem-z"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kerem-z"

# Reading Files
include:
  - _pages
  

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      mathjax: true  # Add this line to enable MathJax for _pages
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: true 
      mathjax: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: false
      share: true

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme  # Add this line if it's not already there

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Add MathJax support
markdown: kramdown
kramdown:
  math_engine: mathjax

# MathJax configuration
mathjax: true
