title: Kerem Zengin
email: kerem.zengin@metu.edu.tr
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website. I'm Kerem 
baseurl: "" # the subpath of your site, e.g. /blog
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  kerem-z

# Theme settings
minimal_mistakes_skin: "dark" # You can change this to other skins if preferred

# Site Author
author:
  name             : "Kerem Zengin"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : 
  location         : "METU"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:kerem.zengin@metu.edu.tr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kerem-z"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kerem-z"


include:
  - _pages
  

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      mathjax: true  # Add this line to enable MathJax for _pages
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: true 
      mathjax: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: false
      share: true

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme 
